config/routes.rb
Rails.application.routes.draw do

   root 'blog_posts#index'
   resources :blog_posts

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.all
  end
  def new
    puts "this is the controller"
    @blog_post = BlogPost.new
  end

  def create
  blog_post = BlogPost.new
  blog_post.save
  redirect_to blog_posts_path
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path
    else
      render :edit
    end
  end

  def destroy
    blog_post = BlogPost.find(params[:id])

    blog_post.destroy
      redirect_to blog_post_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :author, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
Edit a post:
<%= form_for @blog_post do |f| %>
<div>
  <%= f.label :title  %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :author %>
  <%= f.text_field :author %>
</div>

<div>
  <%= f.label :content %>
  <%= f.text_area :content %>
</div>

<%= f.submit "Edit Blog Post" %>
<% end %>

app/views/blog_posts/index.html.erb
Index
<% @blog_posts.each do |blog_post| %>
<div>
  <p><%= blog_post.title %></p>
  <p><%= blog_post.author %></p>
  <%= link_to blog_post.title, blog_post %>
</div>
<hr>
<% end %>

app/views/blog_posts/new.html.erb
Create new post:

<%= form_for (BlogPost.new, html: {class: } do |f| %>
<div>
  <!-- example for how to make changes to label -->
  <%= f.label :title, "FOO", class: "green" %>
  <%= f.text_field :title %>
</div>

<div>
  <%= f.label :author %>
  <%= f.text_field :author %>
</div>

<div>
  <%= f.label :content %>
  <%= f.text_area :content %>
</div>

<%= f.submit "Create Blog Post" %>
<% end %>

app/views/blog_posts/show.html.erb
A single Blog Post:

<p><%= @blog_post.title %></p>
<p><%= @blog_post.author %></p>
<p><%= @blog_post.content %></p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %>
<%= link_to 'Delete', blog_post_path(@blog_post), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>